In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('NULOS.csv')
df

   EDAD     PAIS SEXO COVID
0  28.0   ESPAÑA    H    SI
1   NaN  FRANCIA    M    NO
2  15.0   ESPAÑA    H    SI
3   NaN   ESPAÑA    H    NO
4   NaN  FRANCIA    M    SI
5   NaN  FRANCIA    M   NaN

In [ ]:
df.isnull().sum()

EDAD     4
PAIS     0
SEXO     0
COVID    1
dtype: int64

In [ ]:
df.shape

(6, 4)

In [ ]:
df.fillna(0)

   EDAD     PAIS SEXO COVID
0  28.0   ESPAÑA    H    SI
1   0.0  FRANCIA    M    NO
2  15.0   ESPAÑA    H    SI
3   0.0   ESPAÑA    H    NO
4   0.0  FRANCIA    M    SI
5   0.0  FRANCIA    M     0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   EDAD    2 non-null      float64
 1   PAIS    6 non-null      object
 2   SEXO    6 non-null      object
 3   COVID   5 non-null      object
dtypes: float64(1), object(3)
memory usage: 320.0+ bytes

In [ ]:
df.dropna()

   EDAD    PAIS SEXO COVID
0  28.0  ESPAÑA    H    SI
2  15.0  ESPAÑA    H    SI

In [ ]:
df.dropna(1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.dropna will be keyword-only
  """Entry point for launching an IPython kernel.

      PAIS SEXO
0   ESPAÑA    H
1  FRANCIA    M
2   ESPAÑA    H
3   ESPAÑA    H
4  FRANCIA    M
5  FRANCIA    M

In [ ]:
X = df.drop('COVID',axis=1)
Y = df['COVID']
X

   EDAD     PAIS SEXO
0  28.0   ESPAÑA    H
1   NaN  FRANCIA    M
2  15.0   ESPAÑA    H
3   NaN   ESPAÑA    H
4   NaN  FRANCIA    M
5   NaN  FRANCIA    M

In [ ]:
#Separar el dataframe en train y test
train,test=train_test_split(df,random_state=10, train_size=0.75)

In [ ]:
train

   EDAD     PAIS SEXO COVID
0  28.0   ESPAÑA    H    SI
3   NaN   ESPAÑA    H    NO
4   NaN  FRANCIA    M    SI
1   NaN  FRANCIA    M    NO

In [ ]:
test

   EDAD     PAIS SEXO COVID
2  15.0   ESPAÑA    H    SI
5   NaN  FRANCIA    M   NaN